"""Export settings shared by the FusionToDescription pipeline."""

from dataclasses import dataclass, field
from typing import List


@dataclass
class ExportConfig:
    robot_name: str
    export_directory: str
    package_name: str = ""
    ros_distro: str = "jazzy"
    gazebo_version: str = "harmonic"
    generate_xacro: bool = True
    generate_urdf: bool = True
    generate_rviz: bool = True
    generate_gazebo: bool = True
    generate_launch: bool = True
    generate_ros2_control: bool = True
    collision_type: str = "Primitive"
    primitive_mode: str = "Auto Detect"
    mesh_collision: bool = False
    mesh_format: str = "stl"
    mesh_quality: str = "high"
    binary_mesh: bool = True
    overwrite_existing: bool = True
    export_hidden_components: bool = False
    export_only_visible: bool = True
    package_version: str = "0.1.0"
    maintainer_name: str = "FusionToDescription"
    maintainer_email: str = "noreply@example.com"
    license: str = "Apache-2.0"
    description: str = "Robot description package generated by FusionToDescription."
    enabled_plugins: List[str] = field(default_factory=list)
    enabled_sensors: List[str] = field(default_factory=list)
    enabled_controllers: List[str] = field(default_factory=list)

    def __post_init__(self):
        if not self.package_name:
            self.package_name = f"{self.robot_name}_description"

    def package_directory(self):
        return f"{self.export_directory}/{self.package_name}"

    def mesh_directory(self):
        return f"{self.package_directory()}/meshes"

    def urdf_directory(self):
        return f"{self.package_directory()}/urdf"

    def launch_directory(self):
        return f"{self.package_directory()}/launch"

    def config_directory(self):
        return f"{self.package_directory()}/config"

    def rviz_directory(self):
        return f"{self.package_directory()}/rviz"

    def worlds_directory(self):
        return f"{self.package_directory()}/worlds"
