"""
package_xml_generator.py

Generates package.xml for a ROS 2 robot description package.
Target:
    - ROS 2 Jazzy
    - Gazebo Harmonic
"""

from .file_writer import FileWriter


class PackageXMLGenerator:

    def __init__(
        self,
        robot,
        package_creator
    ):

        self.robot = robot
        self.package = package_creator

        self.writer = FileWriter(
            self.package.package_directory()
        )

    # =====================================================
    # Generate package.xml
    # =====================================================

    def generate(self):

        xml = self._build_xml()

        self.writer.write_file(
            "package.xml",
            xml
        )

    # =====================================================
    # Build XML
    # =====================================================

    def _build_xml(self):

        dependencies = self._dependencies()

        xml = f"""<?xml version="1.0"?>
<package format="3">

<name>{self.robot.package_name}</name>

<version>0.1.0</version>

<description>
    Robot description package generated by FusionToDescription.
</description>

<maintainer email="user@example.com">
    USER_NAME
</maintainer>

<license>Apache-2.0</license>

{dependencies}

<export>

    <build_type>ament_cmake</build_type>

</export>

</package>
"""

        return xml

    # =====================================================
    # Dependencies
    # =====================================================

    def _dependencies(self):

        deps = [

"ament_cmake",
"robot_state_publisher",
"joint_state_publisher",
"joint_state_publisher_gui",
"rviz2",
"xacro",
"urdf"

        ]

        # Gazebo Harmonic

        if getattr(self.robot, "generate_gazebo", False):

            deps.extend([
"ros_gz_sim",
"ros_gz_bridge"
            ])

        # ros2_control

        if getattr(self.robot, "generate_control", False):

            deps.extend([
"controller_manager",
"joint_state_broadcaster",
"joint_trajectory_controller",
"ros2_control",
"ros2_controllers"
            ])

        xml = ""

        for dep in sorted(set(deps)):

            xml += f"  <depend>{dep}</depend>\n"

        return xml